import os
print("Call Job Scroller Scripts")
os.system("C:\\Users\\shortma1\\PycharmProjects\\ScrollerParser\\JobListScrollerMTP.py")
print("MTP Scroller Script ran.")
os.system("C:\\Users\\shortma1\\PycharmProjects\\ScrollerParser\\JobListScrollerParis.py")
print("Paris Scroller Script ran.")
os.system("C:\\Users\\shortma1\\PycharmProjects\\ScrollerParser\\JobListScrollerSS.py")
print("SS Scroller Script ran.")
os.system("C:\\Users\\shortma1\\PycharmProjects\\ScrollerParser\\JobListScrollerTXK.py")
print("TXK Scroller Script ran.")
print("All done.")